# Downloading dependencies
- name: wal-g dependencies
  become: yes
  apt:
    pkg:
      - liblzo2-dev
      - libsodium-dev
      - cmake

# install go dependency for WAL-G
- name: wal-g go dependency
  get_url:
    url: "https://golang.org/dl/go{{ golang_version }}.linux-{{ platform }}.tar.gz"
    dest: /tmp
    checksum: "{{ golang_version_checksum[platform] }}"
    timeout: 60

- name: unpack go archive
  unarchive:
    remote_src: yes
    src: "/tmp/go{{ golang_version }}.linux-{{ platform }}.tar.gz"
    dest: /usr/local

# Download WAL-G
- name: wal-g - download latest version
  git:
    repo: https://github.com/wal-g/wal-g.git
    dest: /tmp/wal-g
    version: "{{ wal_g_release }}"
  become: yes

- name: wal-g - additional go dependencies
  make:
    chdir: /tmp/wal-g
    target: deps
    params:
      GOBIN: "/usr/local/bin"
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      USE_LIBSODIUM: true
  become: yes
  ignore_errors: yes

- name: wal-g - build
  make:
    chdir: /tmp/wal-g
    target: pg_build
    jobs: "{{ parallel_jobs | default(omit) }}"
    params:
      GOBIN: "/usr/local/bin"
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      USE_LIBSODIUM: true
  become: yes

- name: wal-g - install
  make:
    chdir: /tmp/wal-g
    target: pg_install
    params:
      GOBIN: "/usr/local/bin"
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      USE_LIBSODIUM: true
  become: yes

# Create pgbouncer user
- name: Create wal-g user
  user:
    name: wal-g
    shell: /bin/false
    comment: WAL-G user
    groups: postgres

- name: Give postgres access to execute wal-g binary as wal-g user
  copy:
    content: |
      postgres   ALL=(wal-g) NOPASSWD: /usr/local/bin/wal-g
    dest: /etc/sudoers.d/postgres

- name: Create a config directory owned by wal-g
  file:
    path: /etc/wal-g
    state: directory
    owner: wal-g
    mode: '0700'

- name: Create /etc/wal-g/config.json
  file:
    path: /etc/wal-g/config.json
    state: touch
    owner: wal-g
    mode: '0700'

- name: Create logs dir
  become: yes
  file:
    path: /var/log/wal-g
    state: directory
    owner: wal-g

- name: Create backup-push.log
  file:
    path: /var/log/wal-g/backup-push.log
    state: touch
    owner: wal-g
    mode: '0700'

- name: Create backup-fetch.log
  file:
    path: /var/log/wal-g/backup-fetch.log
    state: touch
    owner: wal-g
    mode: '0700'

- name: Create wal-push.log
  file:
    path: /var/log/wal-g/wal-push.log
    state: touch
    owner: wal-g
    mode: '0700'

- name: Create wal-fetch.log
  file:
    path: /var/log/wal-g/wal-fetch.log
    state: touch
    owner: wal-g
    mode: '0700'

# Clean up Go
- name: Uninstall Go
  become: yes
  file:
    path: /usr/local/go
    state: absent
